/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollectorRouteImport } from './routes/collector'
import { Route as ReceiverRouteImport } from './routes/receiver'
import { Route as CollectorIndexRouteImport } from './routes/collector.index'
import { Route as CollectorDealRouteImport } from './routes/collector.deal'
import { Route as CollectorLotsRouteImport } from './routes/collector.lots'
import { Route as CollectorNewRouteImport } from './routes/collector.new'
import { Route as CollectorProfileRouteImport } from './routes/collector.profile'
import { Route as DocumentsIdRouteImport } from './routes/documents.$id'
import { Route as ReceiverIndexRouteImport } from './routes/receiver.index'
import { Route as ReceiverDealRouteImport } from './routes/receiver.deal'
import { Route as ReceiverRecyclingRouteImport } from './routes/receiver.recycling'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorRoute = CollectorRouteImport.update({
  id: '/collector',
  path: '/collector',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiverRoute = ReceiverRouteImport.update({
  id: '/receiver',
  path: '/receiver',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorIndexRoute = CollectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorDealRoute = CollectorDealRouteImport.update({
  id: '/deal',
  path: '/deal',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorLotsRoute = CollectorLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorNewRoute = CollectorNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorProfileRoute = CollectorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CollectorRoute,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiverIndexRoute = ReceiverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceiverRoute,
} as any)
const ReceiverDealRoute = ReceiverDealRouteImport.update({
  id: '/deal',
  path: '/deal',
  getParentRoute: () => ReceiverRoute,
} as any)
const ReceiverRecyclingRoute = ReceiverRecyclingRouteImport.update({
  id: '/recycling',
  path: '/recycling',
  getParentRoute: () => ReceiverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/collector': typeof CollectorRouteWithChildren
  '/receiver': typeof ReceiverRouteWithChildren
  '/collector/deal': typeof CollectorDealRoute
  '/collector/lots': typeof CollectorLotsRoute
  '/collector/new': typeof CollectorNewRoute
  '/collector/profile': typeof CollectorProfileRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/receiver/deal': typeof ReceiverDealRoute
  '/receiver/recycling': typeof ReceiverRecyclingRoute
  '/collector/': typeof CollectorIndexRoute
  '/receiver/': typeof ReceiverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/collector/deal': typeof CollectorDealRoute
  '/collector/lots': typeof CollectorLotsRoute
  '/collector/new': typeof CollectorNewRoute
  '/collector/profile': typeof CollectorProfileRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/receiver/deal': typeof ReceiverDealRoute
  '/receiver/recycling': typeof ReceiverRecyclingRoute
  '/collector': typeof CollectorIndexRoute
  '/receiver': typeof ReceiverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/collector': typeof CollectorRouteWithChildren
  '/receiver': typeof ReceiverRouteWithChildren
  '/collector/deal': typeof CollectorDealRoute
  '/collector/lots': typeof CollectorLotsRoute
  '/collector/new': typeof CollectorNewRoute
  '/collector/profile': typeof CollectorProfileRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/receiver/deal': typeof ReceiverDealRoute
  '/receiver/recycling': typeof ReceiverRecyclingRoute
  '/collector/': typeof CollectorIndexRoute
  '/receiver/': typeof ReceiverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/collector'
    | '/receiver'
    | '/collector/deal'
    | '/collector/lots'
    | '/collector/new'
    | '/collector/profile'
    | '/documents/$id'
    | '/receiver/deal'
    | '/receiver/recycling'
    | '/collector/'
    | '/receiver/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/collector/deal'
    | '/collector/lots'
    | '/collector/new'
    | '/collector/profile'
    | '/documents/$id'
    | '/receiver/deal'
    | '/receiver/recycling'
    | '/collector'
    | '/receiver'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/collector'
    | '/receiver'
    | '/collector/deal'
    | '/collector/lots'
    | '/collector/new'
    | '/collector/profile'
    | '/documents/$id'
    | '/receiver/deal'
    | '/receiver/recycling'
    | '/collector/'
    | '/receiver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CollectorRoute: typeof CollectorRouteWithChildren
  ReceiverRoute: typeof ReceiverRouteWithChildren
  DocumentsIdRoute: typeof DocumentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector': {
      id: '/collector'
      path: '/collector'
      fullPath: '/collector'
      preLoaderRoute: typeof CollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiver': {
      id: '/receiver'
      path: '/receiver'
      fullPath: '/receiver'
      preLoaderRoute: typeof ReceiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/': {
      id: '/collector/'
      path: '/'
      fullPath: '/collector/'
      preLoaderRoute: typeof CollectorIndexRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/deal': {
      id: '/collector/deal'
      path: '/deal'
      fullPath: '/collector/deal'
      preLoaderRoute: typeof CollectorDealRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/lots': {
      id: '/collector/lots'
      path: '/lots'
      fullPath: '/collector/lots'
      preLoaderRoute: typeof CollectorLotsRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/new': {
      id: '/collector/new'
      path: '/new'
      fullPath: '/collector/new'
      preLoaderRoute: typeof CollectorNewRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/profile': {
      id: '/collector/profile'
      path: '/profile'
      fullPath: '/collector/profile'
      preLoaderRoute: typeof CollectorProfileRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiver/': {
      id: '/receiver/'
      path: '/'
      fullPath: '/receiver/'
      preLoaderRoute: typeof ReceiverIndexRouteImport
      parentRoute: typeof ReceiverRoute
    }
    '/receiver/deal': {
      id: '/receiver/deal'
      path: '/deal'
      fullPath: '/receiver/deal'
      preLoaderRoute: typeof ReceiverDealRouteImport
      parentRoute: typeof ReceiverRoute
    }
    '/receiver/recycling': {
      id: '/receiver/recycling'
      path: '/recycling'
      fullPath: '/receiver/recycling'
      preLoaderRoute: typeof ReceiverRecyclingRouteImport
      parentRoute: typeof ReceiverRoute
    }
  }
}

interface CollectorRouteChildren {
  CollectorDealRoute: typeof CollectorDealRoute
  CollectorLotsRoute: typeof CollectorLotsRoute
  CollectorNewRoute: typeof CollectorNewRoute
  CollectorProfileRoute: typeof CollectorProfileRoute
  CollectorIndexRoute: typeof CollectorIndexRoute
}

const CollectorRouteChildren: CollectorRouteChildren = {
  CollectorDealRoute: CollectorDealRoute,
  CollectorLotsRoute: CollectorLotsRoute,
  CollectorNewRoute: CollectorNewRoute,
  CollectorProfileRoute: CollectorProfileRoute,
  CollectorIndexRoute: CollectorIndexRoute,
}

const CollectorRouteWithChildren = CollectorRoute._addFileChildren(
  CollectorRouteChildren,
)

interface ReceiverRouteChildren {
  ReceiverDealRoute: typeof ReceiverDealRoute
  ReceiverRecyclingRoute: typeof ReceiverRecyclingRoute
  ReceiverIndexRoute: typeof ReceiverIndexRoute
}

const ReceiverRouteChildren: ReceiverRouteChildren = {
  ReceiverDealRoute: ReceiverDealRoute,
  ReceiverRecyclingRoute: ReceiverRecyclingRoute,
  ReceiverIndexRoute: ReceiverIndexRoute,
}

const ReceiverRouteWithChildren = ReceiverRoute._addFileChildren(
  ReceiverRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CollectorRoute: CollectorRouteWithChildren,
  ReceiverRoute: ReceiverRouteWithChildren,
  DocumentsIdRoute: DocumentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
